#!/Users/josiehen/anaconda/bin/python
# -------------------------------------------------------
#PREAMBLE

import numpy as np
import MDAnalysis
from MDAnalysis.analysis import hbonds
import matplotlib.pyplot as plt

pdb = syst.argv[1] #parameter file (truncated.prmtop?)
traj = syst.argv[2] #production run to analyze

#MAIN

u = MDAnalysis.Universe('%s' %(pdb), '%s' %(traj))        #Make Universe for single prod run
H = u.select_atoms('name Hn')                             #Selection for hydrogens and donors
pro = u.select_atoms('protein and name O or name N')      #Selection for acceptors in protein

hb_auto = hbonds.HydrogenBondAutoCorrel(u, acceptors = pro, hydrogens = H, donors = H, bond_type = 'continuous', nsamples = '1000')  #Do things!

hb_auto.run()           #Actually run the thing, hopefully
hb_auto.solve()         #Fit results to multi exponential decay, integrate

results = hb_auto.solution('results')    #Raw results of autocorrelation
time = hb_auto.solution('time')          #Axis for results in ps

plt.plot(time, results, 'ro')            #Plot things
plt.show()                               #What

save_results(filename = 'hbond_test')







